name: auto_generated_assets_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1


flutter_gen:
  output: lib/resources/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)


  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
  assets:
    output:
      enabled: true
      package_parameter_enabled: true
      style: camel-case

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/domine/Domine-Regular.ttf
        - weight: 400
        - asset: assets/fonts/domine/Domine-Medium.ttf
        - weight: 500
        - asset: assets/fonts/domine/Domine-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/domine/Domine-Bold.ttf
        - weight: 700